FROM quay.io/keycloak/keycloak:24.0.5 AS builder

RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:24.0.5
LABEL MAINTAINER="Entando <dev@entando.com>"
ARG VERSION
LABEL name="Entando Keycloak" \
      vendor="Entando" \
      version="v${VERSION}" \
      release="7.3" \
      summary="Keycloak with Entando's themes and extensions." \
      description="This is container hosts Keycloak along with themes created for Entando."
COPY LICENSE /licences/entando-lgpl.txt

COPY themes/entando /opt/keycloak/themes/entando
COPY --from=builder /opt/keycloak/ /opt/keycloak/

COPY docker-entrypoint.sh /opt/docker-entrypoint.sh
COPY convert-vars.sh /opt/convert-vars.sh

USER root
RUN chmod +x /opt/docker-entrypoint.sh /opt/convert-vars.sh
USER keycloak

ENV KC_SPI_THEME_DEFAULT="entando" \
    KEYCLOAK_HOME="/opt/keycloak"

ENTRYPOINT ["/opt/docker-entrypoint.sh"]
