FROM quay.io/keycloak/keycloak:23.0.3 as builder

RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:23.0.3

COPY themes/entando /opt/keycloak/themes/entando
COPY --from=builder /opt/keycloak/ /opt/keycloak/

ENV KC_SPI_THEME_DEFAULT="entando"

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
