FROM registry.redhat.io/rh-sso-7/sso76-openshift-rhel8:7.6-20
LABEL MAINTAINER="Entando <dev@entando.com>"
ARG VERSION
LABEL name="Entando Red Hat SSO" \
      vendor="Entando" \
      version="v${VERSION}" \
      release="7" \
      summary="Red Hat SSO with Entando's themes and extensions." \
      description="This is container hosts Red Hat SSO along with themes created for Entando."
COPY --chown=185:0 LICENSE /licences/entando-lgpl.txt
COPY --chown=185:0 themes /opt/eap/themes
COPY --chown=185:0 redhat-sso/modules/ /opt/eap/modules/system/layers/openshift/
COPY --chown=185:0 redhat-sso/standalone-openshift.xml /opt/eap/standalone/configuration/standalone-openshift.xml
COPY --chown=185:0 redhat-sso/datasource-common.sh /opt/eap/bin/launch/datasource-common.sh

ARG MYSQL_JDBC_DRIVER_VERSION=8.0.22
ARG ORACLE_JDBC_DRIVER_VERSION=21.4.0.0.1
RUN curl https://repo1.maven.org/maven2/mysql/mysql-connector-java/${MYSQL_JDBC_DRIVER_VERSION}/mysql-connector-java-${MYSQL_JDBC_DRIVER_VERSION}.jar -o /opt/eap/modules/system/layers/openshift/com/mysql/main/mysql-connector-java.jar
RUN curl https://repo1.maven.org/maven2/com/oracle/database/jdbc/ojdbc8/${ORACLE_JDBC_DRIVER_VERSION}/ojdbc8-${ORACLE_JDBC_DRIVER_VERSION}.jar -o /opt/eap/modules/system/layers/openshift/com/oracle/main/ojdbc8.jar
RUN mkdir -p /opt/eap/modules/system/layers/com/ongres/scram/common/2.1/ \
 && curl https://repo1.maven.org/maven2/com/ongres/scram/common/2.1/common-2.1.jar -o /opt/eap/modules/system/layers/com/ongres/scram/common/2.1/common-2.1.jar

COPY LICENSE /licenses/entando-lgpl.txt
ENV KEYCLOAK_DEFAULT_THEME="entando" \
    KEYCLOAK_HOME="/opt/eap"

