version: '3.3'
services:
  keycloak:
    build:
      context: ./
      dockerfile: Dockerfile.keycloak
    hostname: keycloak
    ports:
      - "8081:8080"
    command:
      - start
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: qwe123
      KC_HTTP_RELATIVE_PATH: "/auth"
      KC_HOSTNAME_STRICT: "false"
      KC_PROXY: "edge"
      
      # Other database connection parameters
      #KC_DB: <DB_TYPE>
      #KC_DB_URL: <URL>
      #KC_DB_SCHEMA: <SCHEMA> # for postgresql
      #KC_DB_USERNAME: username
      #KC_DB_PASSWORD: password
