version: '3.3'
services:
  keycloak:
    build:
      context: ./
      dockerfile: Dockerfile.keycloak
    hostname: keycloak
    ports:
      - "8081:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: qwe123
      DB_VENDOR: h2
      PROXY_ADDRESS_FORWARDING: "true"

      # Other database connection parameters
      #DB_ADDR: "db-host"
      #DB_PORT: 3306
      #DB_DATABASE: keycloak
      #DB_USER: username
      #DB_PASSWORD: password
