name: PUB

on:
  push:
    tags:
      - "v*"

env:
  PPL_TEMPLATE_VERSION: "v2.0.0"
  ENTANDO_BOT_TOKEN: ${{ secrets.ENTANDO_BOT_TOKEN }}
  PR_CHECKER_PATH: ".github/pr-title-checker-config.json"

  DOCKER_KEYCLOAK_IMAGE_BASE_NAME: entando/entando-keycloak
  DOCKER_SSO_IMAGE_BASE_NAME: entando/entando-redhat-sso
  DOCKER_IMAGE_ARCHITECTURE: linux/amd64,linux/arm64
  DOCKER_KEYCLOAK_IMAGE_ARCHITECTURE: ${{ env.DOCKER_IMAGE_ARCHITECTURE }}
  DOCKER_SSO_IMAGE_ARCHITECTURE: linux/amd64
  DOCKER_IMAGE_CONTEXT: .
  DOCKER_KEYCLOAK_IMAGE_FILE: Dockerfile.keycloak
  DOCKER_SSO_IMAGE_FILE: Dockerfile.redhat-sso
  DOCKER_IMAGE_PUSH: true

jobs:

  check-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: thehanimo/pr-title-checker@v1.3.7
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pass_on_octokit_error: false
          configuration_path: ${{ env.PR_CHECKER_PATH }}

  publication:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta-keycloak
        id: meta-keycloak
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.DOCKER_KEYCLOAK_IMAGE_BASE_NAME }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr,value={{base_ref}}
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
            type=raw,event=pr,value={{base_ref}}

      - name: Docker meta-sso
        id: meta-sso
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.DOCKER_SSO_IMAGE_BASE_NAME }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
            type=raw,event=pr,value={{branch}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: ${{ env.DOCKER_IMAGE_ARCHITECTURE }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.ENTANDO_OPT_DOCKER_USERNAME }}
          password: ${{ secrets.ENTANDO_OPT_DOCKER_PASSWORD }}

      - name: Login to RHT
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ENTANDO_RHT_DOCKER_REGISTRY }}
          username: ${{ secrets.ENTANDO_RHT_DOCKER_USERNAME }}
          password: ${{ secrets.ENTANDO_RHT_DOCKER_PASSWORD }}

      - name: Build keycloak
        uses: docker/build-push-action@v4
        with:
          context: ${{ env.DOCKER_IMAGE_CONTEXT }}
          file: ${{ env.DOCKER_KEYCLOAK_IMAGE_FILE }}
          push: ${{ env.DOCKER_IMAGE_PUSH }}
          tags: ${{ steps.meta-keycloak.outputs.tags }}
          labels: ${{ steps.meta-keycloak.outputs.labels }}
          platforms: ${{ env.DOCKER_KEYCLOAK_IMAGE_ARCHITECTURE }}

      - name: Build sso
        uses: docker/build-push-action@v4
        with:
          context: ${{ env.DOCKER_IMAGE_CONTEXT }}
          file: ${{ env.DOCKER_SSO_IMAGE_FILE }}
          push: ${{ env.DOCKER_IMAGE_PUSH }}
          tags: ${{ steps.meta-sso.outputs.tags }}
          labels: ${{ steps.meta-sso.outputs.labels }}
          platforms: ${{ env.DOCKER_SSO_IMAGE_ARCHITECTURE }}